spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./target/database;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    username: sa
    password: pw
  servlet:
    multipart:
      max-file-size: -1
      enabled: false
  h2:
    console.enabled: true

save-dir: ./target/files